name: LuminAIR Benchmarks
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write
  pages: write

jobs:
  benchmark:
    name: Run LuminAIR benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-01-02
          override: true
          profile: minimal

      - name: Run benchmark
        run: |
          cd crates/graph
          cargo bench --bench ops -- --output-format bencher | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: LuminAIR Benchmarks
          tool: "cargo"
          output-file-path: crates/graph/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "150%"
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: "@gizatechxyz"
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: bench
